#!/usr/bin/env python3
"""Compile load.c + engine.c (one translation unit) to the GNU-as source
the build links (load.s). --check refuses a stale load.s."""
import pathlib
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
FLAGS = ["-mcpu=54455", "-O2", "-DEV=4", "-ffreestanding", "-fno-builtin", "-fno-common",
         "-fno-jump-tables", "-fno-asynchronous-unwind-tables", "-fno-ident",
         "-fomit-frame-pointer", "-fno-zero-initialized-in-bss", "-Wall", "-Wextra", "-Werror"]


def main():
    check = "--check" in sys.argv
    with tempfile.TemporaryDirectory() as tmp:
        unit = pathlib.Path(tmp) / "unit.c"
        unit.write_text('#include "load.c"\n#include "engine.c"\n')
        dest = pathlib.Path(tmp) / "load.s"
        # run in HERE with relative names: the inline asm's line markers
        # carry the source path into load.s
        unit.write_text('#include "load.c"\n#include "engine.c"\n')
        subprocess.run(["m68k-elf-gcc", *FLAGS, "-I", ".", "-S", "-x", "c", "-o", str(dest), "-"],
                       input=unit.read_text(), text=True, check=True, cwd=HERE)
        body = "| Generated by generate.py; edit load.c / engine.c.\n" + dest.read_text()
    out = HERE / "load.s"
    if check:
        if not out.exists() or out.read_text() != body:
            raise SystemExit(f"stale: {out}")
        print("WAVE LOAD generated source matches")
    else:
        out.write_text(body)
        print("WAVE LOAD source generated")


if __name__ == "__main__":
    main()
