| Generated by generate.py; edit load.c / engine.c.
#NO_APP
	.file	"unit.c"
	.text
	.align	2
	.globl	eng_cmds
	.type	eng_cmds, @function
eng_cmds:
	lea (-12,%sp),%sp
	move.l 24(%sp),%d1
	movem.l #1036,(%sp)
	move.l 16(%sp),%a2
	move.l 20(%sp),%a0
	tst.l %d1
	jle .L1
.L27:
	move.w (%a0),%a1
	moveq #7,%d2
	mvs.w %a1,%d0
	cmp.l %d0,%d2
	jeq .L3
	jlt .L4
	moveq #3,%d3
	cmp.l %d0,%d3
	jeq .L5
	jlt .L6
	mvs.w 2(%a0),%d2
	moveq #1,%d3
	cmp.l %d0,%d3
	jeq .L7
	subq.l #2,%d0
	tst.l %d0
	jeq .L8
	move.w %a1,%d0
	jne .L10
	moveq #44,%d0
	muls.l %d0,%d2
	lea (4,%a0),%a1
	move.l (%a1),4(%a2,%d2.l)
.L10:
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
.L1:
	movem.l (%sp),#1036
	lea (12,%sp),%sp
	rts
.L4:
	moveq #11,%d2
	cmp.l %d0,%d2
	jeq .L14
	jlt .L15
	moveq #9,%d3
	cmp.l %d0,%d3
	jeq .L16
	moveq #10,%d2
	cmp.l %d0,%d2
	jeq .L33
	move.l 4(%a0),208(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L6:
	moveq #5,%d2
	cmp.l %d0,%d2
	jeq .L11
	subq.l #6,%d0
	tst.l %d0
	jeq .L34
	move.l 4(%a0),224(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L15:
	moveq #13,%d3
	cmp.l %d0,%d3
	jeq .L19
	moveq #14,%d2
	cmp.l %d0,%d2
	jeq .L20
	moveq #12,%d3
	cmp.l %d0,%d3
	jne .L10
	move.l 180(%a2),%d0
	tst.l 188(%a2)
	jeq .L22
	move.l #479,%d3
	cmp.l 192(%a2),%d3
	jlt .L22
	add.l 4(%a0),%d0
	tst.l %d0
	jlt .L35
	moveq #32,%d2
	cmp.l %d0,%d2
	jge .L36
	moveq #32,%d0
	moveq #1,%d2
	move.l %d0,180(%a2)
	move.l %d2,188(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L14:
	move.l 4(%a0),252(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L20:
	move.l #67108864,%d0
	subq.l #1,%d1
	move.l #1073741824,%d2
	addq.l #8,%a0
	move.l %d0,240(%a2)
	move.l %d0,236(%a2)
	move.l %d2,204(%a2)
	tst.l %d1
	jne .L27
	jra .L1
.L19:
	move.l 4(%a0),176(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L5:
	move.l 4(%a0),220(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L7:
	moveq #44,%d0
	subq.l #1,%d1
	muls.l %d0,%d2
	lea (4,%a0),%a1
	addq.l #8,%a0
	move.l (%a1),8(%a2,%d2.l)
	tst.l %d1
	jne .L27
	jra .L1
.L8:
	moveq #44,%d0
	subq.l #1,%d1
	muls.l %d0,%d2
	lea (4,%a0),%a1
	addq.l #8,%a0
	move.l (%a1),20(%a2,%d2.l)
	tst.l %d1
	jne .L27
	jra .L1
.L3:
	move.l 4(%a0),216(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L33:
	move.l 4(%a0),248(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L16:
	move.l 4(%a0),244(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L34:
	move.l 4(%a0),200(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L11:
	move.l 4(%a0),212(%a2)
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L22:
	move.l %d0,184(%a2)
	moveq #32,%d2
	add.l 4(%a0),%d0
	move.l %d0,180(%a2)
	cmp.l %d0,%d2
	jlt .L37
	tst.l %d0
	jlt .L38
	moveq #1,%d3
	move.l %d0,180(%a2)
	move.l %d3,188(%a2)
	clr.l 192(%a2)
.L39:
	subq.l #1,%d1
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L37:
	moveq #32,%d0
	moveq #1,%d3
	move.l %d0,180(%a2)
	move.l %d3,188(%a2)
	clr.l 192(%a2)
	jra .L39
.L38:
	clr.l %d0
	moveq #1,%d3
	move.l %d0,180(%a2)
	move.l %d3,188(%a2)
	clr.l 192(%a2)
	jra .L39
.L35:
	moveq #1,%d0
	subq.l #1,%d1
	clr.l 180(%a2)
	move.l %d0,188(%a2)
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
.L36:
	moveq #1,%d3
	subq.l #1,%d1
	move.l %d0,180(%a2)
	move.l %d3,188(%a2)
	addq.l #8,%a0
	tst.l %d1
	jne .L27
	jra .L1
	.size	eng_cmds, .-eng_cmds
	.align	2
	.globl	eng_render
	.type	eng_render, @function
eng_render:
	lea (-72,%sp),%sp
	movem.l #31996,(%sp)
	move.l 76(%sp),%a4
	tst.l 84(%sp)
	jle .L40
	move.l 180(%a4),%d1
	moveq #12,%d2
	move.l 184(%a4),%d0
	move.l 176(%a4),%a0
	lsl.l %d2,%d1
	lsl.l %d2,%d0
	lea (176,%a4),%a1
	move.l %a1,64(%sp)
	lea (%a0,%d1.l),%a6
	add.l %d0,%a0
	move.l %a0,60(%sp)
.L63:
	move.l 196(%a4),%d3
	move.l %d3,%d0
	asr.l #1,%d0
	eor.l #-1073741824,%d0
	jmi .L80
	add.l %d0,%d0
	move.l 212(%a4),%a0
	move.l %d0,%d1
	add.l #-1073741824,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%a0,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	move.l 204(%a4),%d2
	move.l %d2,%d0
	asr.l #1,%d0
	add.l 200(%a4),%d3
	eor.l #-1073741824,%d0
	move.l %d3,196(%a4)
	tst.l %d0
	jlt .L81
.L43:
	add.l %d0,%d0
	move.l 216(%a4),%a0
	add.l #-1073741824,%d0
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%a0,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	add.l 208(%a4),%d2
	move.l #357913941,%a2
	move.l %d2,204(%a4)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%a2,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	move.l #1488522236,%d2
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%d2,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%d0,%acc0
	movclr.l %acc0,%a1
| 0 "" 2
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a1,%d0,%acc0
	movclr.l %acc0,%a0
| 0 "" 2
#NO_APP
	move.l #1431655765,%d3
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a0,%d3,%acc0
	movclr.l %acc0,%a0
| 0 "" 2
#NO_APP
	asr.l #1,%d1
	add.l #1073741824,%d0
	add.l %a1,%d0
	add.l %a0,%d0
	add.l 220(%a4),%d1
	move.l %d0,56(%sp)
	move.l %d1,%d2
	add.l #2684355,%d2
	cmp.l #263066746,%d2
	jle .L44
.L82:
	move.l #263066746,%d2
.L45:
	lsl.l #3,%d2
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d2,%d2,%acc0
	movclr.l %acc0,%a0
| 0 "" 2
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a0,%d2,%acc0
	movclr.l %acc0,%a0
| 0 "" 2
#NO_APP
	move.l #2040109466,%d4
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d4,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d1,%d1
	move.l %d1,%d0
	add.l #-536870912,%d0
	cmp.l #483183821,%d0
	jle .L46
.L83:
	move.l #483183821,%d0
.L47:
	lsl.l #2,%d0
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%d0,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d0,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	move.l #429497,%d7
	move.l 228(%a4),%a1
	move.l %a0,%d1
	sub.l %a1,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d7,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d1,%a1
	move.l 232(%a4),%d5
	sub.l %d5,%d0
	move.l %a1,228(%a4)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d7,%d0,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	move.l #2147483647,%d1
	add.l %d0,%d5
	move.l 236(%a4),%d0
	sub.l %a1,%d1
	move.l %d5,232(%a4)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d0,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	move.l #67108864,%d2
	sub.l %d1,%d2
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%d2,%acc0
	movclr.l %acc0,%d2
| 0 "" 2
#NO_APP
	lsl.l #5,%d2
	move.l #2147483647,%a0
	move.l 240(%a4),%d1
	sub.l %d5,%a0
	add.l %d2,%d0
	move.l %d0,236(%a4)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a0,%d1,%acc0
	movclr.l %acc0,%a0
| 0 "" 2
#NO_APP
	move.l #67108864,%d4
	sub.l %a0,%d4
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d4,%acc0
	movclr.l %acc0,%d4
| 0 "" 2
#NO_APP
	lsl.l #5,%d4
	move.l 224(%a4),%d2
	move.l %d2,%d3
	asr.l #5,%d3
	add.l %d4,%d1
	move.l %d1,240(%a4)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d2,%d0,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	add.l %d3,%d0
	move.l %d0,52(%sp)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d2,%d1,%acc0
	movclr.l %acc0,%a2
| 0 "" 2
#NO_APP
	move.l 188(%a4),%a5
	add.l %d3,%a2
	tst.l %a5
	jeq .L64
.L84:
	move.l 192(%a4),%d0
	move.l #1118481,%d1
	move.l %a4,%a0
	clr.l %d6
	move.l %a2,44(%sp)
	muls.l %d1,%d0
	move.l %d0,68(%sp)
.L61:
	moveq #21,%d3
	move.l (%a0),%d2
	move.l %d2,%d1
	lsr.l %d3,%d1
	move.l %d2,%d3
	lsr.l #7,%d3
	move.l %d1,%d4
	addq.l #1,%d1
	add.l %d4,%d4
	and.l #16383,%d3
	and.l #2047,%d1
	mvs.w (%a6,%d4.l),%d7
	move.l %d3,48(%sp)
	moveq #12,%d3
	add.l %d1,%d1
	move.l %d7,%d0
	lsl.l %d3,%d0
	move.l %d0,%a3
	mvs.w (%a6,%d1.l),%d0
	sub.l %d7,%d0
	move.l 48(%sp),%d7
	muls.l %d7,%d0
	asr.l #2,%d0
	add.l %d0,%a3
	tst.l %a5
	jeq .L49
	move.l 60(%sp),%a2
	mvs.w (%a2,%d4.l),%d4
	mvs.w (%a2,%d1.l),%d0
	move.l %d4,%d1
	lsl.l %d3,%d1
	sub.l %d4,%d0
	muls.l %d7,%d0
	asr.l #2,%d0
	add.l %d1,%d0
	sub.l %d0,%a3
	move.l 68(%sp),%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a3,%d1,%acc0
	movclr.l %acc0,%a3
| 0 "" 2
#NO_APP
	move.l %d0,%a2
	lea (%a2,%a3.l*2),%a3
.L49:
	move.l 4(%a0),%d1
	move.l 56(%sp),%d0
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d0,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	move.l %d2,%a2
	lea (%a2,%d1.l*2),%a2
	move.l 20(%a0),%d0
	move.l 24(%a0),%d1
	move.l %a2,(%a0)
	tst.l %d0
	jeq .L50
	tst.l %d1
	jne .L76
	move.l 12(%a0),%d2
	moveq #1,%d1
	move.l %d1,16(%a0)
	move.l %d0,24(%a0)
.L53:
	move.l 248(%a4),%d1
	sub.l %d2,%d1
	move.l 244(%a4),%d0
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%d1,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	add.l %d0,%d2
	cmp.l #134217728,%d2
	jle .L57
	moveq #2,%d7
	move.l #134217728,%d2
	move.l %d7,16(%a0)
	move.l %d2,12(%a0)
.L58:
	move.l 8(%a0),%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a3,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d2,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	lsl.l #4,%d1
.L60:
	move.l 28(%a0),%d2
	move.l %d2,%d3
	move.l 32(%a0),%d0
	sub.l %d0,%d3
	move.l 52(%sp),%d4
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d4,%d3,%acc0
	movclr.l %acc0,%d3
| 0 "" 2
#NO_APP
	lsl.l #5,%d3
	sub.l %d2,%d1
	add.l %d3,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a1,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d1,%d2
	move.l %d2,%d1
	sub.l %d0,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a1,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d1,%d0
	move.l 36(%a0),%d4
	move.l %d4,%d1
	move.l 40(%a0),%d3
	sub.l %d3,%d1
	move.l 44(%sp),%d7
	move.l %d2,28(%a0)
	move.l %d0,32(%a0)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d7,%d1,%acc0
	movclr.l %acc0,%d2
| 0 "" 2
#NO_APP
	lsl.l #5,%d2
	move.l %d0,%d1
	sub.l %d4,%d1
	add.l %d2,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d5,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d4,%d1
	move.l %d1,%d2
	sub.l %d3,%d2
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d5,%d2,%acc0
	movclr.l %acc0,%d2
| 0 "" 2
#NO_APP
	add.l %d2,%d3
	move.l %d1,36(%a0)
	move.l %d3,40(%a0)
	sub.l %d1,%d0
	add.l %d0,%d6
	lea (44,%a0),%a0
	cmp.l 64(%sp),%a0
	jne .L61
.L85:
	tst.l %a5
	jeq .L62
	move.l 192(%a4),%d0
	addq.l #1,%d0
	move.l %d0,192(%a4)
	cmp.l #959,%d0
	jle .L62
	clr.l 188(%a4)
.L62:
	asr.l #3,%d6
	move.l 80(%sp),%a0
	subq.l #1,84(%sp)
	addq.l #4,80(%sp)
	move.l %d6,(%a0)+
	tst.l 84(%sp)
	jne .L63
.L40:
	movem.l (%sp),#31996
	lea (72,%sp),%sp
	rts
.L81:
	neg.l %d0
	add.l %d0,%d0
	move.l 216(%a4),%a0
	add.l #-1073741824,%d0
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%a0,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	add.l 208(%a4),%d2
	move.l #357913941,%a2
	move.l %d2,204(%a4)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%a2,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	move.l #1488522236,%d2
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%d2,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%d0,%acc0
	movclr.l %acc0,%a1
| 0 "" 2
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a1,%d0,%acc0
	movclr.l %acc0,%a0
| 0 "" 2
#NO_APP
	move.l #1431655765,%d3
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a0,%d3,%acc0
	movclr.l %acc0,%a0
| 0 "" 2
#NO_APP
	asr.l #1,%d1
	add.l #1073741824,%d0
	add.l %a1,%d0
	add.l %a0,%d0
	add.l 220(%a4),%d1
	move.l %d0,56(%sp)
	move.l %d1,%d2
	add.l #2684355,%d2
	cmp.l #263066746,%d2
	jgt .L82
.L44:
	tst.l %d2
	jge .L45
	clr.l %d2
	lsl.l #3,%d2
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d2,%d2,%acc0
	movclr.l %acc0,%a0
| 0 "" 2
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a0,%d2,%acc0
	movclr.l %acc0,%a0
| 0 "" 2
#NO_APP
	move.l #2040109466,%d4
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d4,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d1,%d1
	move.l %d1,%d0
	add.l #-536870912,%d0
	cmp.l #483183821,%d0
	jgt .L83
.L46:
	tst.l %d0
	jge .L47
	clr.l %d0
	lsl.l #2,%d0
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%d0,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d0,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	move.l #429497,%d7
	move.l 228(%a4),%a1
	move.l %a0,%d1
	sub.l %a1,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d7,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d1,%a1
	move.l 232(%a4),%d5
	sub.l %d5,%d0
	move.l %a1,228(%a4)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d7,%d0,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	move.l #2147483647,%d1
	add.l %d0,%d5
	move.l 236(%a4),%d0
	sub.l %a1,%d1
	move.l %d5,232(%a4)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d0,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	move.l #67108864,%d2
	sub.l %d1,%d2
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%d2,%acc0
	movclr.l %acc0,%d2
| 0 "" 2
#NO_APP
	lsl.l #5,%d2
	move.l #2147483647,%a0
	move.l 240(%a4),%d1
	sub.l %d5,%a0
	add.l %d2,%d0
	move.l %d0,236(%a4)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a0,%d1,%acc0
	movclr.l %acc0,%a0
| 0 "" 2
#NO_APP
	move.l #67108864,%d4
	sub.l %a0,%d4
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d4,%acc0
	movclr.l %acc0,%d4
| 0 "" 2
#NO_APP
	lsl.l #5,%d4
	move.l 224(%a4),%d2
	move.l %d2,%d3
	asr.l #5,%d3
	add.l %d4,%d1
	move.l %d1,240(%a4)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d2,%d0,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	add.l %d3,%d0
	move.l %d0,52(%sp)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d2,%d1,%acc0
	movclr.l %acc0,%a2
| 0 "" 2
#NO_APP
	move.l 188(%a4),%a5
	add.l %d3,%a2
	tst.l %a5
	jne .L84
.L64:
	clr.l 68(%sp)
	move.l %a4,%a0
	clr.l %d6
	move.l %a2,44(%sp)
	jra .L61
.L80:
	neg.l %d0
	add.l %d0,%d0
	move.l 212(%a4),%a0
	move.l %d0,%d1
	add.l #-1073741824,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%a0,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	move.l 204(%a4),%d2
	move.l %d2,%d0
	asr.l #1,%d0
	add.l 200(%a4),%d3
	eor.l #-1073741824,%d0
	move.l %d3,196(%a4)
	tst.l %d0
	jge .L43
	jra .L81
.L76:
	move.l 16(%a0),%d1
	moveq #1,%d4
	move.l 12(%a0),%d2
	move.l %d0,24(%a0)
	cmp.l %d1,%d4
	jeq .L53
	moveq #3,%d0
	cmp.l %d1,%d0
	jeq .L55
	tst.l %d1
	jne .L58
	move.l 28(%a0),%d2
	move.l %d2,%d3
	move.l 32(%a0),%d0
	sub.l %d0,%d3
	move.l 52(%sp),%d4
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d4,%d3,%acc0
	movclr.l %acc0,%d3
| 0 "" 2
#NO_APP
	lsl.l #5,%d3
	sub.l %d2,%d1
	add.l %d3,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a1,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d1,%d2
	move.l %d2,%d1
	sub.l %d0,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a1,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d1,%d0
	move.l 36(%a0),%d4
	move.l %d4,%d1
	move.l 40(%a0),%d3
	sub.l %d3,%d1
	move.l 44(%sp),%d7
	move.l %d2,28(%a0)
	move.l %d0,32(%a0)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d7,%d1,%acc0
	movclr.l %acc0,%d2
| 0 "" 2
#NO_APP
	lsl.l #5,%d2
	move.l %d0,%d1
	sub.l %d4,%d1
	add.l %d2,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d5,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d4,%d1
	move.l %d1,%d2
	sub.l %d3,%d2
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d5,%d2,%acc0
	movclr.l %acc0,%d2
| 0 "" 2
#NO_APP
	add.l %d2,%d3
	move.l %d1,36(%a0)
	move.l %d3,40(%a0)
	sub.l %d1,%d0
	add.l %d0,%d6
	lea (44,%a0),%a0
	cmp.l 64(%sp),%a0
	jne .L61
	jra .L85
.L50:
	tst.l %d1
	jeq .L76
	move.l 12(%a0),%d2
	moveq #3,%d3
	move.l %d3,16(%a0)
	clr.l 24(%a0)
.L55:
	move.l #-1342177,%d1
	move.l 252(%a4),%d0
	sub.l %d2,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d0,%d1,%acc0
	movclr.l %acc0,%d0
| 0 "" 2
#NO_APP
	add.l %d0,%d2
	tst.l %d2
	jlt .L86
.L57:
	move.l 8(%a0),%d1
	move.l %d2,12(%a0)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a3,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d1,%d2,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	lsl.l #4,%d1
	jra .L60
.L86:
	move.l 28(%a0),%d2
	clr.l %d1
	move.l 32(%a0),%d0
	move.l %d2,%d3
	move.l 52(%sp),%d4
	sub.l %d0,%d3
	clr.l 16(%a0)
	clr.l 12(%a0)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d4,%d3,%acc0
	movclr.l %acc0,%d3
| 0 "" 2
#NO_APP
	lsl.l #5,%d3
	sub.l %d2,%d1
	add.l %d3,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a1,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d1,%d2
	move.l %d2,%d1
	sub.l %d0,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %a1,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d1,%d0
	move.l 36(%a0),%d4
	move.l %d4,%d1
	move.l 40(%a0),%d3
	sub.l %d3,%d1
	move.l 44(%sp),%d7
	move.l %d2,28(%a0)
	move.l %d0,32(%a0)
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d7,%d1,%acc0
	movclr.l %acc0,%d2
| 0 "" 2
#NO_APP
	lsl.l #5,%d2
	move.l %d0,%d1
	sub.l %d4,%d1
	add.l %d2,%d1
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d5,%d1,%acc0
	movclr.l %acc0,%d1
| 0 "" 2
#NO_APP
	add.l %d4,%d1
	move.l %d1,%d2
	sub.l %d3,%d2
#APP
| 13 "/Users/sambanks/git/octabam/.claude/worktrees/chompi-load/modules/waveload/engine.c" 1
	mac.l %d5,%d2,%acc0
	movclr.l %acc0,%d2
| 0 "" 2
#NO_APP
	add.l %d2,%d3
	move.l %d1,36(%a0)
	move.l %d3,40(%a0)
	sub.l %d1,%d0
	add.l %d0,%d6
	lea (44,%a0),%a0
	cmp.l 64(%sp),%a0
	jne .L61
	jra .L85
	.size	eng_render, .-eng_render
	.align	2
	.globl	cl_frame
	.type	cl_frame, @function
cl_frame:
	lea (-72,%sp),%sp
	movem.l #31996,(%sp)
	move.l 76(%sp),%d4
	tst.l %d4
	jle .L87
	moveq #12,%d0
	cmp.l %d4,%d0
	jlt .L99
	move.l #inst+1048576,%d0
	clr.l %d3
	and.l #-65536,%d0
	moveq #12,%d6
	swap %d6
	move.l %sp,%d5
	clr.l %d2
	lea ready,%a2
	add.l #48,%d5
	lea inst+176,%a5
	lea eng_cmds,%a3
	move.l %d0,44(%sp)
.L94:
	move.l (%a2)+,%d7
	lea (-176,%a5),%a6
	tst.l %d7
	jeq .L100
.L90:
	tst.l 12(%a5)
	jeq .L92
	move.l #479,%d0
	cmp.l 16(%a5),%d0
	jge .L93
.L92:
	pea 1.w
	moveq #1,%d0
	move.l %d5,-(%sp)
	move.l %d6,56(%sp)
	move.l %d0,60(%sp)
	move.l %a6,-(%sp)
	jsr (%a3)
	lea (12,%sp),%sp
.L93:
	pea 16.w
	pea scratch
	move.l %a6,-(%sp)
	jsr eng_render
	addq.l #1,%d2
	lea (256,%a5),%a5
	add.l #135168,%d3
	lea (12,%sp),%sp
	cmp.l %d4,%d2
	jlt .L94
.L87:
	movem.l (%sp),#31996
	lea (72,%sp),%sp
	rts
.L100:
	pea 10.w
	pea setup
	move.l %a6,-(%sp)
	move.l 56(%sp),%d0
	add.l %d3,%d0
	move.l %d0,(%a5)
	jsr (%a3)
	lea note_inc,%a4
	lea (12,%sp),%sp
.L91:
	pea 3.w
	clr.w %d0
	move.l %d5,-(%sp)
	move.l %a6,-(%sp)
	move.w %d7,62(%sp)
	move.w %d7,70(%sp)
	move.w %d7,78(%sp)
	move.l (%a4)+,64(%sp)
	move.w %d0,60(%sp)
	move.l #338186154,%d0
	addq.l #1,%d7
	move.l %d0,72(%sp)
	moveq #1,%d0
	move.l %d0,80(%sp)
	move.w %d0,68(%sp)
	moveq #2,%d0
	move.w %d0,76(%sp)
	jsr (%a3)
	lea (12,%sp),%sp
	moveq #4,%d0
	cmp.l %d7,%d0
	jne .L91
	moveq #1,%d0
	move.l %d0,-4(%a2)
	jra .L90
.L99:
	move.l #inst+1048576,%d0
	moveq #12,%d4
	and.l #-65536,%d0
	move.l %sp,%d5
	clr.l %d3
	moveq #12,%d6
	swap %d6
	lea ready,%a2
	clr.l %d2
	lea inst+176,%a5
	add.l #48,%d5
	lea eng_cmds,%a3
	move.l %d0,44(%sp)
	jra .L94
	.size	cl_frame, .-cl_frame
	.section	.rodata
	.align	2
	.type	setup, @object
	.size	setup, 80
setup:
	.word	14
	.word	0
	.long	0
	.word	6
	.word	0
	.long	481913
	.word	8
	.word	0
	.long	481913
	.word	5
	.word	0
	.long	644245094
	.word	7
	.word	0
	.long	1073741824
	.word	4
	.word	0
	.long	1938103992
	.word	3
	.word	0
	.long	375809638
	.word	9
	.word	0
	.long	99362
	.word	10
	.word	0
	.long	1383784776
	.word	11
	.word	0
	.long	162313
	.align	2
	.type	note_inc, @object
	.size	note_inc, 16
note_inc:
	.long	25480119
	.long	32102938
	.long	38177043
	.long	48100060
	.section	.data,"aw"
	.align	2
	.type	ready, @object
	.size	ready, 48
ready:
	.zero	48
	.align	2
	.type	scratch, @object
	.size	scratch, 64
scratch:
	.zero	64
	.align	2
	.type	inst, @object
	.size	inst, 3072
inst:
	.zero	3072
